### ISSUE TITLE
Pull udev rules from ublue-os/config

### ISSUE THREAD

**Issue by OmegaSquad82** [OmegaSquad82/bluebuilds#36]
```
modules:
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/config:latest /files/ublue-os/udev-rules /
```
